name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Ejecutar deploy en el servidor
      run: |
        ssh -o StrictHostKeyChecking=no root@104.236.101.38 << 'EOF'
          cd /root/Portafolio
          
          git pull origin main

          # Crear archivo .env con la SECRET_KEY del repositorio
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
          echo "DEBUG=${{ secrets.DEBUG }}" >> .env
          echo "ADMIN_USER=${{ secrets.ADMIN_USER }}" >> .env
          echo "ADMIN_PASS_HASH=${{ secrets.ADMIN_PASS_HASH }}" >> .env

          # Activar entorno virtual
          source venv/bin/activate

          # Instalar/actualizar dependencias
          pip install -r requirements.txt

          # Reiniciar gunicorn para aplicar cambios
          systemctl restart gunicorn
        EOF
