name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Ejecutar deploy en el servidor
      run: |
        ssh -o StrictHostKeyChecking=no root@104.236.101.38 << 'EOF'
          cd /root/Portafolio
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          systemctl restart gunicorn
        EOF
